#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

sed -i "s/.*linkit$//g" /etc/opkg/distfeeds.conf

[ "$(uci get system.@system[-1].linkit_firstboot)" = "1" ] && return 0

board=$(cat /tmp/sysinfo/board_name)

uci set system.@system[-1].hostname="mylinkit"
uci set wireless.radio0.disabled=0
uci set network.lan.ipaddr=192.168.100.1

uci delete wireless.default_radio0

uci set wireless.ap=wifi-iface
uci	set wireless.ap.device=radio0
uci	set wireless.ap.network=lan
uci	set wireless.ap.mode=ap
uci	set wireless.ap.ssid=OpenWrt
uci	set wireless.ap.encryption=none

uci	set wireless.sta=wifi-iface
uci	set wireless.sta.device=radio0
uci	set wireless.sta.network=wan
uci	set wireless.sta.mode=sta
uci	set wireless.sta.ssid=RFN
uci	set wireless.sta.encryption=none
uci	set wireless.sta.disabled=1

SSID=`fw_printenv -n wifi_ssid`
KEY=`fw_printenv -n wifi_key`
SEQ=`fw_printenv -n wifi_seq`
[ -n "${SSID}" ] || { \
	MAC=$(dd bs=1 skip=7 count=3 if=/dev/mtd2 2>/dev/null | hexdump -v -n 3 -e '3/1 "%02X"')
	SSID=RFN_Smart_${MAC}
}
[ -n "${SEQ}" ] || \
	SEQ=1
uci set wireless.ap.ssid="$SSID"
uci set wireless.ap.seq="$SEQ"

[ -n "${KEY}" ] && {
	uci set wireless.ap.encryption='psk2'
	uci set wireless.ap.key="$KEY"
}

uci set network.wan=interface
uci set network.wan.proto=dhcp

uci commit

echo "Turning modem ON" > /dev/console
modem_ctrl on

sleep 10

echo "Checking modem" > /dev/console
if [ -c "/dev/ttyACM0" ] || [ -c "/dev/cdc-wdm0" ]; then
	echo "Configuring 4G interface" > /dev/console
	uci set network.4G=interface
	uci set network.4G.proto='modemmanager'
	uci set network.globals.packet_steering='1'
	uci set network.4G.device='/sys/devices/platform/101c0000.ehci/usb1/1-1/1-1.2'
	uci set network.4G.apn='uinternet'
	uci add_list network.4G.allowedauth='none'
	uci set network.4G.iptype='ipv4'
	uci set network.4G.loglevel='ERR'
	
	uci add firewall zone # =cfg0edc81
	uci set firewall.@zone[-1].name='4G'
	uci set firewall.@zone[-1].input='ACCEPT'
	uci set firewall.@zone[-1].output='ACCEPT'
	uci set firewall.@zone[-1].forward='ACCEPT'
	uci add_list firewall.@zone[-1].network='4G'
	
	uci add firewall forwarding # =cfg0fad58
	uci set firewall.@forwarding[-1].src='4G'
	uci set firewall.@forwarding[-1].dest='lan'
	uci add firewall forwarding # =cfg10ad58
	uci set firewall.@forwarding[-1].src='4G'
	uci set firewall.@forwarding[-1].dest='wan'
	uci add firewall forwarding # =cfg11ad58
	uci set firewall.@forwarding[-1].src='lan'
	uci set firewall.@forwarding[-1].dest='4G'
	uci add firewall forwarding # =cfg12ad58
	uci set firewall.@forwarding[-1].src='wan'
	uci set firewall.@forwarding[-1].dest='4G'
	uci set firewall.cfg0edc81.input='ACCEPT'
	uci set firewall.cfg0edc81.forward='ACCEPT'
	uci set firewall.cfg0edc81.masq='1'
	uci set firewall.cfg0edc81.mtu_fix='1'
	
	uci commit
fi

return 0
