#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

sed -i "s/.*linkit$//g" /etc/opkg/distfeeds.conf

uci delete uhttpd.main.alias
uci commit uhttpd

[ "$(uci get system.@system[-1].linkit_firstboot)" = "1" ] && return 0

. /lib/ramips.sh
board=$(ramips_board_name)

uci set system.@system[-1].hostname="mylinkit"
uci set wireless.radio0.disabled=0
uci set network.lan.ipaddr=192.168.100.1


uci set mountd.mountd.path=/Media/

uci commit
return 0
