#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

sed -i "s/.*linkit$//g" /etc/opkg/distfeeds.conf

uci delete uhttpd.main.alias
uci commit uhttpd

[ "$(uci get system.@system[-1].linkit_firstboot)" = "1" ] && return 0

. /lib/ramips.sh
board=$(ramips_board_name)

uci set system.@system[-1].hostname="mylinkit"
uci set wireless.radio0.disabled=0
uci set network.lan.ipaddr=192.168.100.1

uci delete wireless.default_radio0

uci set wireless.ap=wifi-iface
uci	set wireless.ap.device=radio0
uci	set wireless.ap.network=lan
uci	set wireless.ap.mode=ap
uci	set wireless.ap.ssid=OpenWrt
uci	set wireless.ap.encryption=none
			
uci	set wireless.sta=wifi-iface
uci	set wireless.sta.device=radio0
uci	set wireless.sta.network=wan
uci	set wireless.sta.mode=sta
uci	set wireless.sta.ssid=RFN
uci	set wireless.sta.encryption=none
uci	set wireless.sta.disabled=1

SSID=`fw_printenv -n wifi_ssid`
KEY=`fw_printenv -n wifi_key`
SEQ=`fw_printenv -n wifi_seq`
[ -n "${SSID}" ] || { \
	MAC=$(dd bs=1 skip=7 count=3 if=/dev/mtd2 2>/dev/null | hexdump -v -n 3 -e '3/1 "%02X"')
	SSID=RFN_Smart_${MAC}
}
[ -n "${SEQ}" ] || \
	SEQ=1
uci set wireless.ap.ssid="$SSID"
uci set wireless.ap.seq="$SEQ"

[ -n "${KEY}" ] && {
	uci set wireless.ap.encryption='psk2'
	uci set wireless.ap.key="$KEY"
}

uci set network.wan=interface
uci set network.wan.proto=dhcp

uci set mountd.mountd.path=/Media/

uci commit
return 0
