#!/bin/sh

LDR_VER=`strings /dev/mtd0 2>/dev/null | grep -m 1 "U-Boot" | awk '{print $2}'`
[ -z "${LDR_VER}" ] && LDR_VER=1.1.3

uci set system.@system[0].firmware_version=v0.9.4
uci set system.@system[0].loader_version=v${LDR_VER}
uci set system.@system[0].linkit_firstboot=1
uci commit system
