#!/bin/sh

modem_ctrl on	
sleep 1
	
[ -e "/dev/cdc-wdm0" ] && [ "$(uci -q get network.4G)" = "" ] && {
    	# Add 4G interface
    	echo "Adding 4G interface"
	uci set network.4G=interface
	uci set network.4G.proto='qmi'
	uci set network.4G.auth='both'
	uci set network.4G.apn='uinternet'
	uci set network.4G.device='/dev/cdc-wdm0'
	uci set network.4G.pdptype='ipv4'
	
	[ "$(uci -q get firewall.@zone[2])" = "" ] && {
		uci add firewall zone
		uci set firewall.@zone[-1].name='4G'
		uci set firewall.@zone[-1].network='4G'
		uci set firewall.@zone[-1].input='ACCEPT'
		uci set firewall.@zone[-1].output='ACCEPT'
		uci set firewall.@zone[-1].forward='ACCEPT'
		uci set firewall.@zone[-1].masq='1'
	        uci set firewall.@zone[-1].mtu_fix='1'
		
		uci add firewall forwarding
		uci set firewall.@forwarding[-1].src='4G'
		uci set firewall.@forwarding[-1].dest='lan'
		
		uci add firewall forwarding
		uci set firewall.@forwarding[-1].src='4G'
		uci set firewall.@forwarding[-1].dest='wan'
		
		uci add firewall forwarding
		uci set firewall.@forwarding[-1].src='lan'
		uci set firewall.@forwarding[-1].dest='4G'
		
		uci add firewall forwarding
		uci set firewall.@forwarding[-1].src='wan'
		uci set firewall.@forwarding[-1].dest='4G'
	}
	uci commit
	luci-reload
}

[ -e "/dev/ttyACM3" ] && [ "$(uci -q get network.3G)" = "" ] && {
    	# Add 3G interface
    	echo "Adding 3G interface"
	uci set network.3G=interface
	uci set network.3G.proto='3g'
	uci set network.3G.service='umts'
	uci set network.3G.apn='uinternet'
	uci set network.3G.device='/dev/ttyACM3'
	
	[ "$(uci -q get firewall.@zone[2])" = "" ] && {
		uci add firewall zone
		uci set firewall.@zone[-1].name='3G'
		uci set firewall.@zone[-1].network='3G'
		uci set firewall.@zone[-1].input='ACCEPT'
		uci set firewall.@zone[-1].output='ACCEPT'
		uci set firewall.@zone[-1].forward='ACCEPT'
		uci set firewall.@zone[-1].masq='1'
        	uci set firewall.@zone[-1].mtu_fix='1'
		
		uci add firewall forwarding
		uci set firewall.@forwarding[-1].src='3G'
		uci set firewall.@forwarding[-1].dest='lan'
		
		uci add firewall forwarding
		uci set firewall.@forwarding[-1].src='3G'
		uci set firewall.@forwarding[-1].dest='wan'
		
		uci add firewall forwarding
		uci set firewall.@forwarding[-1].src='lan'
		uci set firewall.@forwarding[-1].dest='3G'
		
		uci add firewall forwarding
		uci set firewall.@forwarding[-1].src='wan'
		uci set firewall.@forwarding[-1].dest='3G'
	}
	uci commit
	luci-reload
}

uci set firewall.@defaults[0].forward='ACCEPT'
uci set firewall.@zone[1].forward='ACCEPT'
uci add firewall forwarding
uci set firewall.@forwarding[-1].src='wan'
uci set firewall.@forwarding[-1].dest='lan'
uci commit
luci-reload

return 0
